# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
# Check github actions and pip on main
  - package-ecosystem: "github-actions" 
    directory: ".github/workflows/" 
    schedule:
      interval: "weekly"
    target-branch: "main"  
  - package-ecosystem: "pip" 
    directory: ".github/workflows/" 
    schedule:
      interval: "weekly"
    target-branch: "main" 
# Check github actions and pip on Arcticons-Pages
  - package-ecosystem: "github-actions" 
    directory: ".github/workflows/"
    schedule:
      interval: "weekly"
    target-branch: "Arcticons-Pages"  
  - package-ecosystem: "pip" 
    directory: ".github/workflows/" 
    schedule:
      interval: "weekly"
    target-branch: "Arcticons-Pages"  
#gradle dependencies on main
  - package-ecosystem: "gradle" 
    directory: "app/" 
    schedule:
      interval: "weekly"
    target-branch: "main" 
  - package-ecosystem: "gradle" 
    directory: "preparehelper/" 
    schedule:
      interval: "weekly"
    target-branch: "main" 
