name: Build Nightly
on:
  schedule:
    - cron: '00 12 * * 6'
  workflow_dispatch:

permissions:
  actions: none
  attestations: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
concurrency:
  group: 'nightly'
  cancel-in-progress: false
jobs:
  buildNightly:
    name: Build Arcticons APK Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Write sign info
        run: "echo \"Workflow manually triggered by ${{ github.actor }}\"\nif [ ! -z \"${{ secrets.KEYSTORE }}\" ]; then\n  echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties\n  echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties\n  echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties\n  echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties\n  echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks\nfi   \n"
      - name: Get Gradle
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Prepare Release Helper
        run: ./gradlew :preparehelper:preparerelasenew
      - name: Build Normal APK
        run: ./gradlew app:assemblenormalNightly
      - name: Build Black APK
        run: ./gradlew app:assembleblackNightly
      - name: Build You APK
        run: ./gradlew app:assembleyouNightly
      - name: Build Day&Night
        run: ./gradlew app:assembledayNightNightly
      - name: Delete old nightly release and tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG_NAME="nightly"
          # Delete the release and the associated tag if they exist
          gh release delete "$TAG_NAME" --yes --cleanup-tag || true
          git push origin --delete "$TAG_NAME" || true
      - name: Make Prerelease
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG_NAME="nightly"
          NAME="Automated Prerelease"
          NOTES="This is an automatically generated nightly prelease to help try out changes since the last main release."
          gh release create $TAG_NAME --prerelease --generate-notes --fail-on-no-commits --title "$NAME" --notes "$NOTES" --target "$GITHUB_SHA" app/build/outputs/apk/normal/nightly/*.apk app/build/outputs/apk/black/nightly/*.apk app/build/outputs/apk/dayNight/nightly/*.apk app/build/outputs/apk/you/nightly/*.apk