name: Update Colormapping

on:
  push:
    branches: ["Arcticons-Pages"]
    paths:
      - 'docs/extracted_png/*'
      - 'docs/assets/request.txt'
  workflow_dispatch:
    inputs:
      run_colormapping:
        description: "Run Create_Colormappping job (true/false)"
        required: false
        default: "true"
      run_requestjson:
        description: "Run Create_requestjson job (true/false)"
        required: false
        default: "true"

permissions:
  contents: write
concurrency:
  group: 'updaterequest'
  cancel-in-progress: false

jobs:
  Create_Colormappping:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_colormapping == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      colormapping_done: ${{ steps.colormapping_done.outcome }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: Arcticons-Pages
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r .github/workflows/requirements.txt
      
      - name: Execute Python Script
        id: colormapping_done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/workflows/create_colormapping.py

      - name: Upload Colormapping
        uses: actions/upload-artifact@v4
        with:
          name: colormapping
          path: docs/assets/image_color_counts.xml

  Create_requestjson:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_requestjson == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      requestjson_done: ${{ steps.requestjson_done.outcome }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: Arcticons-Pages
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r .github/workflows/requirements.txt
      
      - name: Execute Python Script
        id: requestjson_done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/workflows/getGPlayData.py

      - name: Upload Requestjson
        uses: actions/upload-artifact@v4
        with:
          name: requestjson
          path: docs/assets/requests.json

  Push_Files:
    needs: [Create_Colormappping, Create_requestjson]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: Arcticons-Pages
      
      - name: Download Colormapping and Requestjson
        uses: actions/download-artifact@v4
        with:
          path: docs/assets
          merge-multiple: true

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Automated updates from Colormappping and Requestjson jobs"
          git push
